version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./media:/app/media   # 🔹 host <-> container paylaşımı

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.api.processor.tasks.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./media:/app/media   # 🔹 aynı volume’u worker’a da mount et

  redis:
    image: redis:7
    container_name: redis_broker
    ports:
      - "6380:6379"

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
